# Generated by Django 4.2.6 on 2023-10-31 21:41

from django.db import migrations, models
import django.db.models.deletion
import usuarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=500)),
                ('DPI', models.IntegerField(unique=True, validators=[usuarios.models.validate_dpi])),
                ('Nacimiento', models.CharField(max_length=10)),
                ('Direccion', models.CharField(max_length=150)),
                ('Razon', models.TextField(max_length=1000)),
                ('Receta', models.ImageField(upload_to='')),
                ('Tel', models.IntegerField(validators=[usuarios.models.validate_tel])),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Fecha_Actual', models.CharField(max_length=10)),
                ('Nombre_Medico', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=500)),
                ('No_colegiado', models.IntegerField(unique=True, validators=[usuarios.models.validate_cole])),
                ('Diagnostico', models.TextField(max_length=1500)),
                ('Tel', models.IntegerField(validators=[usuarios.models.validate_tel])),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Nombre_Paciente', models.CharField(max_length=500)),
                ('Especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.especialidad')),
            ],
        ),
    ]
