# Generated by Django 4.2.6 on 2023-11-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=500)),
                ('Asunto', models.CharField(max_length=500)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Razon', models.TextField(max_length=3500)),
            ],
        ),
    ]
